### ISSUE TITLE
Create a brand page 

### ISSUE THREAD

**Issue by Rabbia-tariq96** [Rabbia-tariq96/Project#6]
Create a brand page that will be able to display the brand associated with our gift shop website. Make a entry that would allow us to post our message to our customers i.e. latest deals, upcoming sales. All this information would be then stored onto our data.

**Comment by IqraHabib** [comment]
![screenshot 54](https://user-images.githubusercontent.com/44527726/52124365-ce2cf900-264a-11e9-9763-0917d15ea570.png)
![screenshot 55](https://user-images.githubusercontent.com/44527726/52124373-d2591680-264a-11e9-894d-5d151e854146.png)

Done!
